# Generated by Django 4.2.17 on 2024-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
